#!/usr/bin/python
# encoding: utf-8

import sys
import os
from subprocess import Popen, PIPE

from urllib2 import urlopen
import json

USE_TERM_COLORS = True
DEBUG = False
NO_FORKS = False
NO_ORG_FORKS = True

WHITELIST=[]
BLACKLIST=[]

ACCESS_TOKEN_PARAM = 'access_token=%s'
GITHUB_API_HOST = 'https://api.github.com'

GIT_CLONE_CMD = 'git clone https://%s@github.com/%s'
GIT_LOG_CMD = 'git log origin/{0} -1 --format=%H'
GIT_FETCH_CMD = 'git fetch'

USER_DETAILS_PATH = '/users/%s'

COLOR_BOLD_GREEN = "\033[1;32m"
COLOR_BOLD_BLUE = "\033[1;34m"
COLOR_BOLD_YELLOW = "\033[1;33m"
COLOR_END = "\033[0m"

class AttributeDict(dict):
    def __getattr__(self, attr):
        return self[attr]

def check_parameters(args):
    if len(args) < 3:
        print "No argument provided. Exiting."
        print "Usage: %s <username> <github token>" % args[0]
        exit(1)

def get_json(uri, token):
    if '?' in uri:
        uri += '&' + ACCESS_TOKEN_PARAM % token
    else:
        uri += '?' + ACCESS_TOKEN_PARAM % token

    if DEBUG:
        print "Trying:", uri

    return json.loads(urlopen(uri).read(), object_hook=AttributeDict)

def get_user_data(username, token):
    return get_json(GITHUB_API_HOST + USER_DETAILS_PATH % username, token)

def get_repos(repos_url, orgs_url, token):
    if DEBUG:
        print "Getting repo data from", COLOR_BOLD_GREEN, repos_url, COLOR_END

    orgs = get_json(orgs_url, token)

    repos = get_json(repos_url, token)
    if NO_FORKS:
        repos = [repo for repo in repos if not repo.fork]

    for org in orgs:
        org_repos = get_json(org.repos_url, token)

        priv_org_repos = [repo for repo in org_repos if repo.private]

        if NO_ORG_FORKS:
            priv_org_repos = [repo for repo in priv_org_repos if not repo.fork]

        repos += priv_org_repos

    if DEBUG:
        print "Available repos:", COLOR_BOLD_GREEN + str(len(repos)), COLOR_END
        for repo in repos:
            owner = repo.owner.login
            print " -", COLOR_BOLD_YELLOW + repo.name, COLOR_END
            print " " * 5, repo.description


    return repos

def filter_repo_names(repos):
    if DEBUG:
        print "Filtering..."
        #print repos

    original_repos = len(repos)

    repos = [repo for repo in repos if not repo.name in BLACKLIST]

    if len(WHITELIST) > 0:
        repos = [repo for repo in repos if repo.name in WHITELIST]

    filtered_repos = original_repos - len(repos)

    if filtered_repos:
        print "Filtered", COLOR_BOLD_RED + str(filtered_repos) + COLOR_END, "repos"

    print "Fetching repos:", COLOR_BOLD_GREEN + str(original_repos - filtered_repos), "/", original_repos, \
        "(" + str(filtered_repos), "filtered)", COLOR_END
    for repo in repos:
        owner = repo.owner.login
        print " -", COLOR_BOLD_YELLOW + repo.name, COLOR_END
        print " " * 5, repo.description

    return repos

def try_clone(working_directory, repo_data, token):
    target_directory = os.path.join(working_directory, repo_data.name)
    print "Using directory", target_directory

    if os.path.isdir(target_directory):
        print "Already cloned. Skipping cloning"
        return False

    print "Need to clone", repo_data.name
    system_exec(GIT_CLONE_CMD % (token, repo_data.full_name))

    print "Finished cloning"
    return True

def update_repo(repo_url, token):
    repo_data = get_json(repo_url, token)

    working_directory = system_exec('pwd', None, False)
    if try_clone(working_directory, repo_data, token):
        return

    target_directory = os.path.join(working_directory, repo_data.name)

    old_sha=system_exec(GIT_LOG_CMD.format(repo_data.default_branch), target_directory, False)
    print "Old", COLOR_BOLD_GREEN + repo_data.default_branch + COLOR_END, "SHA", \
        COLOR_BOLD_GREEN + old_sha[:7], COLOR_END

    print "Updating", target_directory, "(" + repo_data.default_branch + ")"
    system_exec(GIT_FETCH_CMD, target_directory, False)

    new_sha=system_exec(GIT_LOG_CMD.format(repo_data.default_branch), target_directory, False)
    print "New", COLOR_BOLD_GREEN + repo_data.default_branch + COLOR_END, "SHA", \
        COLOR_BOLD_GREEN + new_sha[:7], COLOR_END

def system_exec(command, directory=None, show_output=True):
    try:
        if directory:
            p = Popen(command, stdout=PIPE, stderr=PIPE, shell=True, cwd=directory)
        else:
            p = Popen(command, stdout=PIPE, stderr=PIPE, shell=True)

        (output, error) = p.communicate()

        if show_output:
            print output.strip()
            sys.stdout.flush()

        if p.returncode != 0:
            raise Exception(error)
        return output.strip()
    except Exception as e:
        print "Could not execute", command, e
        if DEBUG:
            print "Terminating early"
            exit(1)

if __name__ == '__main__':
    check_parameters(sys.argv)

    username = sys.argv[1]
    token = sys.argv[2]

    print "Updating repos from", COLOR_BOLD_GREEN + username, COLOR_END
    user_data = get_user_data(username, token)

    repos = get_repos(user_data.repos_url, user_data.organizations_url, token)
    repos = filter_repo_names(repos)
    for repo in repos:
        print "-" * 60
        update_repo(repo.url, token)
